# This is a basic workflow to help you get started with Actions
name: Build and Deploy Hugo Site

# Controls when the action will run. Triggers the workflow on push
# events but only for the master branch
on:
  push:
    branches: [ main ]
env:
  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
jobs:
  Build_and_Deploy:
    runs-on: ubuntu-22.04

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      # Sets up Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.102.3'
          extended: true
      # Builds chrisjburns.com repo
      - name: Build
        working-directory: website
        run: hugo --minify
        # Deploys built website to S3
      - name: Setup - gcloud / gsutil
        uses: 'google-github-actions/setup-gcloud@v0'
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GCS_PROJECT }}
          export_default_credentials: true
      - name: Deploy
        working-directory: website
        run: |-
          gsutil -m -h "Cache-Control:no-cache,max-age=0" rsync -R public gs://$GCS_BUCKET
